### ISSUE TITLE
Filter to replace Edit Event Submission Message

### ISSUE THREAD

**Issue by atharalikhichi** [ashokdudhat/wp-event-manager#1]
Hi Team,

Can you help my identifying a filter from that I can change a **_message_** when an organizer clicks on save changes button on **_edit event_**.

I can see that currently it is defined at line # 164 on **_/forms/wp-event-manager-form-edit-event.php_** file.

**Comment by ashokdudhat** [comment]
Please use Wordpress.org for issues.

**Comment by atharalikhichi** [comment]
Can you please share the wordpress link?

**Comment by ashokdudhat** [comment]
https://wordpress.org/support/plugin/wp-event-manager

**Comment by atharalikhichi** [comment]
That means for now, I cannot edit this?

**Comment by ashokdudhat** [comment]
Yes for current version not.
