### ISSUE TITLE
Remove Event Title option on Backend

### ISSUE THREAD

**Issue by monika-12** [ashokdudhat/wp-event-manager#11]
There is no need of Event title option because Event title appearing on fronted through Page Title. This option is not useful here.

![screenshot-testsite local-2018 07 11-16-55-58](https://user-images.githubusercontent.com/17018981/42568651-7a26266c-852b-11e8-9f30-05753e5ae118.png)

![screenshot-testsite local-2018 07 11-16-56-20](https://user-images.githubusercontent.com/17018981/42568658-7efed468-852b-11e8-8abf-50213d5e3107.png)

Event Title appearing from Page Title

![screenshot-testsite local-2018 07 11-16-56-52](https://user-images.githubusercontent.com/17018981/42568673-81805ed2-852b-11e8-9fb0-5b35b6202ad7.png)

**Comment by ashokdudhat** [comment]
Fixed this issue in version 2.5
