### ISSUE TITLE
Add File upload type for Logo Field in Backend dashboard

### ISSUE THREAD

**Issue by monika-12** [ashokdudhat/wp-event-manager#5]
Event Data - Update text field type to file upload field for Logo. 
Actual - There is no option to upload logo file.
Expected - There should be option to upload logo file
![screenshot-testsite local-2018 07 02-12-26-24](https://user-images.githubusercontent.com/17018981/42149284-2d2039fa-7df3-11e8-9afe-4e716ccb6158.png)

**Comment by hiteshmakvana** [comment]
Logo removed from backend fields.
