### ISSUE TITLE
Required Fields not working on Backend

### ISSUE THREAD

**Issue by monika-12** [ashokdudhat/wp-event-manager#6]
Backend - Event Fields - Required condition on fields are not working.
![screenshot-testsite local-2018 07 03-11-02-04](https://user-images.githubusercontent.com/17018981/42200375-92e00c26-7eb0-11e8-8a04-b38c1e298b34.png)
![screenshot-testsite local-2018 07 03-11-02-19](https://user-images.githubusercontent.com/17018981/42200377-95411546-7eb0-11e8-9b4b-c6e4aaae1b19.png)

**Comment by hiteshmakvana** [comment]
Backend side field editor removed in new version so it will only work with frontend.
