### ISSUE TITLE
Enhancement - Mark (*) on Required Fields in Backend 

### ISSUE THREAD

**Issue by monika-12** [ashokdudhat/wp-event-manager#7]
Backend - Make required fields to be visible by (*)
Actual - There is no mark on required fields so it will be confusing for user.
Expected - There should be (*) mark on all Required Fields

**Comment by hiteshmakvana** [comment]
As per the wordpress default functionality we dont want to add this now. Still i am not sure wheather we will add this validation feature to the admin side or not.

I like to use core features of wordpress instead of making it more complicated.
