### ISSUE TITLE
Frontend - Event Banner slider button not working

### ISSUE THREAD

**Issue by monika-12** [ashokdudhat/wp-event-manager#8]
Frontend - Single Event Page - On Multiple Banners images - Slider button not working.
Expected - Slider button should navigation to next banner image.
![screenshot-testsite local-2018 07 03-15-41-51](https://user-images.githubusercontent.com/17018981/42214010-f1163992-7ed7-11e8-8b1d-9ec9c68546ef.png)

**Comment by hiteshmakvana** [comment]
@monika-12 You have faced this issue because you don't have more thumbnail to load from the right side. When you have more than button will work. I have verified.
